let units = {
  humidity_in: "%",
  humidity_out: "%",
  light: "%",
  rain: "mm",
  temperature: "°C",
  wind_direction: "°",
  wind_speed: "m/s",
  Windspeed: "m/s",
  Air_pres_1: "hPa",
  BMP_temp_1: "°C",
  DHT11_hum_1: "%",
  DHT11__temp_1: "°C",
  DS1820_temp_1: "°C",
  HumOut_kry: "%",
  Inn_Temp: "°C",
  Light_MATB_C: "%",
  // Lihapekka: "",
  Wind_dir_MIRC: "°",
  // aargh: "",
  humout_Resisthor: "%",
  WindSpeed_R8: "m/s",
  Inn_Wind_Speed: "m/s",
};

let prettySignalNames = {
  humidity_in: "humidity inside",
  humidity_out: "humidity outside 1",
  light: "light level",
  rain: "rain level",
  temperature: "temperature 1",
  wind_direction: "wind direction 1",
  wind_speed: "wind speed 1",
  Windspeed: "wind speed 2",
  Air_pres_1: "air pressure",
  BMP_temp_1: "BMP temperature",
  DHT11_hum_1: "DHT11 humidity",
  DHT11__temp_1: "DHT11 temperature inside",
  DS1820_temp_1: "DS1820 temperature",
  HumOut_kry: "humidity outside 2",
  Inn_Temp: "temperature 2",
  Light_MATB_C: "light level",
  // Lihapekka: "",
  Wind_dir_MIRC: "wind direction 2",
  // aargh: "",
  humout_Resisthor: "humidity outside 3",
  WindSpeed_R8: "wind speed 3",
  Inn_Wind_Speed: "wind speed 4",
};

let apiBaseUrl = "https://webapi19sa-1.course.tamk.cloud/";

export { units, prettySignalNames, apiBaseUrl };
