version: '2.4'
services:
  webapp:
   image: "${FRONTEND_IMAGE}"
   ports:
     - "80:80"
   restart: always
  api:
    image: "${BACKEND_IMAGE}"
    ports:
      - "9000:9000"
    restart: always
  db:
    image: mysql:8.0.3
    volumes:
        - /var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: db_rootpass
        MYSQL_DATABASE: tietokanta
    restart: always
  mywebsql:
    image: quantumobject/docker-mywebsql
    ports:
        - "9001:80"
    restart: always